/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estadistica.gui;

import estadistica.modelo.Articulo;
import estadistica.modelo.Formulas;
import estadistica.modelo.NombreComparator;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import net.ausiasmarch.common.Convert;

/**
 *
 * @author Programador
 */
public class Main extends javax.swing.JFrame {

    List<Articulo> articulos = new ArrayList();
    List<Articulo> busqueda = new ArrayList();

    /**
     * Creates new form Estadistica
     */
    public Main() {
        initComponents();
        String[] cabeceraTabla = {"Articulo", "Cantidad", "Precio/Unidad", "Precio total", "Total con IVA"};
        gridPrincipal.setColumnIdentifiers(cabeceraTabla);
        gridPrincipal.setNumRows(articulos.size());
        gridBusqueda.setColumnIdentifiers(cabeceraTabla);
        gridBusqueda.setNumRows(busqueda.size());
        setLocationRelativeTo(null);
        setTitle("Control de inventario");
        this.setResizable(false);
        //setSize(763, 630);
        this.validate();
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCantidad = new javax.swing.JTextField();
        jButtonAnadir = new javax.swing.JButton();
        jTextFieldArticulo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jToggleButtonOrdenarArticulo = new javax.swing.JToggleButton();
        jToggleButtonOrdenarPrecio = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButtonOrdenarArticulo1 = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNumArticulos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldMedia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPrecioMax = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldPrecioTotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldModa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldCantTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldPrecioMin = new javax.swing.JTextField();
        jTextFieldVarianza = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButtonCalcular = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldArtBusqueda = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButtonBuscarArt = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldPrecioBusqueda = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldCantBusqueda = new javax.swing.JTextField();
        jComboBoxCompBusqueda = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        gridBusqueda = new estadistica.modelo.Grid();
        jButtonBuscarPrecio = new javax.swing.JButton();
        jButtonBuscarCant = new javax.swing.JButton();
        jTextFieldBorrado = new javax.swing.JTextField();
        jButtonBorrar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridPrincipal = new estadistica.modelo.Grid();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setText("Nombre Artículo");

        jLabel2.setText("Precio/ud");

        jLabel3.setText("Cantidad");

        jButtonAnadir.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButtonAnadir.setText("AÑADIR");
        jButtonAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAnadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24)
                        .addComponent(jTextFieldArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jToggleButtonOrdenarArticulo.setText("Ordenar Articulo");
        jToggleButtonOrdenarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonOrdenarArticuloActionPerformed(evt);
            }
        });

        jToggleButtonOrdenarPrecio.setText("Ordenar Precio/ud");

        jToggleButton1.setText("Ordenar Precio Total");

        jToggleButtonOrdenarArticulo1.setText("Ordenar Existencias");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jToggleButtonOrdenarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButtonOrdenarArticulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jToggleButtonOrdenarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonOrdenarArticulo)
                    .addComponent(jToggleButtonOrdenarArticulo1)
                    .addComponent(jToggleButtonOrdenarPrecio)
                    .addComponent(jToggleButton1))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Estadística"));

        jLabel4.setText("Nº Articulos:");

        jTextFieldNumArticulos.setEditable(false);

        jLabel6.setText("Cant. Total:");

        jTextFieldMedia.setEditable(false);

        jLabel7.setText("Precio/ud Total:");

        jTextFieldPrecioMax.setEditable(false);

        jLabel8.setText("Moda Cantidad:");

        jTextFieldPrecioTotal.setEditable(false);

        jLabel9.setText("Media Precio:");

        jTextFieldModa.setEditable(false);

        jLabel10.setText("Precio Máximo:");

        jTextFieldCantTotal.setEditable(false);

        jLabel11.setText("Precio Mínimo:");

        jTextFieldPrecioMin.setEditable(false);

        jTextFieldVarianza.setEditable(false);

        jLabel12.setText("Varianza:");

        jButtonCalcular.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonCalcular.setText("Calcular estadistica");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldMedia)
                            .addComponent(jTextFieldNumArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addGap(36, 36, 36)
                                .addComponent(jTextFieldCantTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPrecioMax, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 55, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPrecioMin, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldModa, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldVarianza, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldNumArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldCantTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldModa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldPrecioMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldPrecioMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVarianza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCalcular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscador"));

        jLabel5.setText("Artículo:");

        jButtonBuscarArt.setText("Buscar");
        jButtonBuscarArt.setToolTipText("");
        jButtonBuscarArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarArtActionPerformed(evt);
            }
        });

        jLabel15.setText("Precio Total IVA:");

        jLabel17.setText("Cantidad:");

        jComboBoxCompBusqueda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Igual a", "Mayor o igual a", "Menor o igual a", "Mayor a", "Menor a" }));

        gridBusqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(gridBusqueda);

        jButtonBuscarPrecio.setText("Buscar");
        jButtonBuscarPrecio.setToolTipText("");
        jButtonBuscarPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarPrecioActionPerformed(evt);
            }
        });

        jButtonBuscarCant.setText("Buscar");
        jButtonBuscarCant.setToolTipText("");
        jButtonBuscarCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarCantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldArtBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(jButtonBuscarArt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel13)
                        .addGap(70, 70, 70))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonBuscarPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldPrecioBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxCompBusqueda, 0, 173, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonBuscarCant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldCantBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldArtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldPrecioBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldCantBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCompBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuscarArt)
                    .addComponent(jButtonBuscarPrecio)
                    .addComponent(jButtonBuscarCant))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
        );

        jTextFieldBorrado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBorradoKeyReleased(evt);
            }
        });

        jButtonBorrar.setText("Borrar");
        jButtonBorrar.setEnabled(false);
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jButtonLimpiar.setText("Limpiar todo");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jLabel14.setText("Borrar articulo");

        gridPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(gridPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldBorrado, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(jButtonLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldBorrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBorrar)
                    .addComponent(jButtonLimpiar)
                    .addComponent(jButtonSalir))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarArtActionPerformed

        if (jTextFieldArtBusqueda.getText().isEmpty()) {
            mensaje("Este campo de busqueda no puede estar vacio");
            return;
        }
        if (!jTextFieldArtBusqueda.getText().matches("[A-Za-zÁÉÍÓÚáéíóúñÑ]*(\\s[A-Za-zÁÉÍÓÚáéíóúñÑ]+)*")) {
            mensaje("Formato del articulo no válido");
            return;
        }
        String nombre = jTextFieldArtBusqueda.getText();
        limpiarBusqueda();

        for (Articulo a : articulos) {
            if (a.getNombre().equalsIgnoreCase(nombre)) {
                busqueda.add(a);
            }
        }

        resultadosBusqueda();

    }//GEN-LAST:event_jButtonBuscarArtActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed

        if (!jTextFieldBorrado.getText().matches("[A-Za-zÁÉÍÓÚáéíóúñÑ]*(\\s[A-Za-zÁÉÍÓÚáéíóúñÑ]+)*")) {
            mensaje("Formato del articulo no válido");
            return;
        }

        for (Articulo art : articulos) {
            if (art.getNombre().equalsIgnoreCase(jTextFieldBorrado.getText())) {

                articulos.remove(art);
                dibujarGridPrincipal();
                return;
            }
        }
        mensaje("No exite el articulo que quieres borrar.");

    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed

    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas salir?", "Salir", JOptionPane.OK_CANCEL_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {
            dispose();
            System.exit(0);
        }

    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirActionPerformed
// Articulo articulo = new Articulo();

        if (!validar()) {
            return;
        }

        String nombreArticulo = jTextFieldArticulo.getText();
        int cantidad = Convert.parseInt(jTextFieldCantidad.getText());
        float precioUnidad = Convert.parseFloat(jTextFieldPrecio.getText());

        for (Articulo art : articulos) {
            if (art.getNombre().equalsIgnoreCase(jTextFieldArticulo.getText())) {
                mensaje("Este articulo ya existe, se sumara al existente.");

                art.setCantidad(art.getCantidad() + cantidad);
                art.setPrecio_unidad(precioUnidad);
                dibujarGridPrincipal();
                return;
            }
        }

        Articulo articulo = new Articulo(nombreArticulo, cantidad, precioUnidad);
        articulos.add(articulo);

        dibujarGridPrincipal();

    }//GEN-LAST:event_jButtonAnadirActionPerformed

    private void jToggleButtonOrdenarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonOrdenarArticuloActionPerformed

        NombreComparator nombreComp = new NombreComparator();

        for (int i = 0; i < articulos.size() - 1; i++) {

            for (int j = i + 1; i < articulos.size(); i++) {
                if (nombreComp.compare(articulos.get(i), articulos.get(j)) > 0) {
                    Articulo comodin = articulos.get(i);
                    articulos.set(i, articulos.get(j));
                    articulos.set(j, comodin);

                }

            }

        }
        dibujarGridPrincipal();

    }//GEN-LAST:event_jToggleButtonOrdenarArticuloActionPerformed

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        if (articulos.isEmpty()) {
            mensaje("La lista esta vacia, no hay nada que calcular.");
        } else {
            Formulas estadisticas = new Formulas(articulos);

            String numeroDeArticulos, cantidadTotal,
                    precioTotal, modaCantidad, mediaPrecio,
                    precioMax, precioMin, varianza;

            numeroDeArticulos = Convert.format(estadisticas.cantArti());
            cantidadTotal = Convert.format(estadisticas.cantTotal());
            precioTotal = Convert.format(estadisticas.precioTotal(), 2);
            modaCantidad = Convert.format(estadisticas.moda());
            mediaPrecio = Convert.format(estadisticas.mediaPrecio(), 2);
            precioMax = Convert.format(estadisticas.precioMax(), 2);
            precioMin = Convert.format(estadisticas.precioMin(), 2);
            varianza = Convert.format(estadisticas.varianza(), 4);

            jTextFieldNumArticulos.setText(numeroDeArticulos);
            jTextFieldCantTotal.setText(cantidadTotal);
            jTextFieldPrecioTotal.setText(precioTotal);
            jTextFieldModa.setText(modaCantidad);
            jTextFieldMedia.setText(mediaPrecio);
            jTextFieldPrecioMax.setText(precioMax);
            jTextFieldPrecioMin.setText(precioMin);
            jTextFieldVarianza.setText(varianza);

        }
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jTextFieldBorradoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBorradoKeyReleased

        if (!jTextFieldBorrado.getText().isEmpty()) {
            jButtonBorrar.setEnabled(true);
        } else {
            jButtonBorrar.setEnabled(false);
        }
    }//GEN-LAST:event_jTextFieldBorradoKeyReleased

    private void jButtonBuscarPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPrecioActionPerformed

        if (jTextFieldPrecioBusqueda.getText().isEmpty()) {
            mensaje("Este campo de busqueda no puede estar vacio");
            return;
        } else if (!Convert.isValidFloat(jTextFieldPrecioBusqueda.getText())) {
            mensaje("No es un numero valido");
            return;
        }

        float precioIVA = Convert.parseFloat(jTextFieldPrecioBusqueda.getText());

        limpiarBusqueda();

        for (Articulo a : articulos) {
            if (a.getPrecioTotalIVA() == precioIVA) {
                busqueda.add(a);
            }
        }
        resultadosBusqueda();

    }//GEN-LAST:event_jButtonBuscarPrecioActionPerformed

    private void jButtonBuscarCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarCantActionPerformed

        if (jTextFieldCantBusqueda.getText().isEmpty()) {
            mensaje("Este campo de busqueda no puede estar vacio");
            return;
        } else if (!Convert.isValidInt(jTextFieldCantBusqueda.getText())) {
            mensaje("No es un numero valido");
            return;
        }
        int cantidad = Convert.parseInt(jTextFieldCantBusqueda.getText());

        limpiarBusqueda();

        switch (jComboBoxCompBusqueda.getSelectedIndex()) {

            case 0:
                for (Articulo a : articulos) {
                    if (a.getCantidad() == cantidad) {
                        busqueda.add(a);
                    }
                }
                break;
            case 1:
                for (Articulo a : articulos) {
                    if (a.getCantidad() >= cantidad) {
                        busqueda.add(a);
                    }
                }
                break;
            case 2:
                for (Articulo a : articulos) {
                    if (a.getCantidad() <= cantidad) {
                        busqueda.add(a);
                    }
                }
                break;
            case 3:
                for (Articulo a : articulos) {
                    if (a.getCantidad() > cantidad) {
                        busqueda.add(a);
                    }
                }
                break;
            case 4:
                for (Articulo a : articulos) {
                    if (a.getCantidad() < cantidad) {
                        busqueda.add(a);
                    }
                }
                break;

        }

        resultadosBusqueda();

    }//GEN-LAST:event_jButtonBuscarCantActionPerformed

    private void mensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    private boolean validar() {

        if (jTextFieldArticulo.getText().isEmpty()) {
            mensaje("El nombre del articulo no se puede dejar en blanco");
            return false;
        }

        if (!jTextFieldArticulo.getText().matches("[A-Za-zÁÉÍÓÚáéíóúñÑ]*(\\s[A-Za-zÁÉÍÓÚáéíóúñÑ]+)*")) {
            mensaje("Formato del articulo no válido");
            return false;
        }

        if (jTextFieldPrecio.getText().isEmpty()) {
            mensaje("El precio no puede quedarse en blanco");
            return false;
        }

        if (!Convert.isValidDouble(jTextFieldPrecio.getText())) {
            mensaje("El precio no es válido");
            return false;
        }

        if (jTextFieldCantidad.getText().isEmpty()) {
            mensaje("La cantidad no puede quedarse en blanco");
            return false;
        }

        if (!Convert.isValidInt(jTextFieldCantidad.getText())) {
            mensaje("La cantidad no es válida");
            return false;
        }

        return true;
    }

    private void resultadosBusqueda() {
        for (int i = 0; i < busqueda.size(); i++) {
            gridBusqueda.setValueAt(busqueda.get(i).getNombre(), i, 0);
            gridBusqueda.setValueAt(busqueda.get(i).getCantidad(), i, 1);
            gridBusqueda.setValueAt(Convert.format(busqueda.get(i).getPrecio_unidad(), 2), i, 2);
            gridBusqueda.setValueAt(Convert.format(busqueda.get(i).getPrecioTotal(), 2), i, 3);
            gridBusqueda.setValueAt(Convert.format(busqueda.get(i).getPrecioTotalIVA(), 2), i, 4);
        }
    }

    private void limpiarBusqueda() {
        if (!busqueda.isEmpty()) {
            busqueda.clear();
            gridBusqueda.clear();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private estadistica.modelo.Grid gridBusqueda;
    private estadistica.modelo.Grid gridPrincipal;
    private javax.swing.JButton jButtonAnadir;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonBuscarArt;
    private javax.swing.JButton jButtonBuscarCant;
    private javax.swing.JButton jButtonBuscarPrecio;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox jComboBoxCompBusqueda;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldArtBusqueda;
    private javax.swing.JTextField jTextFieldArticulo;
    private javax.swing.JTextField jTextFieldBorrado;
    private javax.swing.JTextField jTextFieldCantBusqueda;
    private javax.swing.JTextField jTextFieldCantTotal;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldMedia;
    private javax.swing.JTextField jTextFieldModa;
    private javax.swing.JTextField jTextFieldNumArticulos;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldPrecioBusqueda;
    private javax.swing.JTextField jTextFieldPrecioMax;
    private javax.swing.JTextField jTextFieldPrecioMin;
    private javax.swing.JTextField jTextFieldPrecioTotal;
    private javax.swing.JTextField jTextFieldVarianza;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButtonOrdenarArticulo;
    private javax.swing.JToggleButton jToggleButtonOrdenarArticulo1;
    private javax.swing.JToggleButton jToggleButtonOrdenarPrecio;
    // End of variables declaration//GEN-END:variables

    private void dibujarGridPrincipal() {
        String cantidad, precioUnidad, precioTotal, precioConIva;
        gridPrincipal.clear();
        for (int i = 0; i < articulos.size(); i++) {
            cantidad = Convert.format(articulos.get(i).getCantidad());
            precioUnidad = Convert.format(articulos.get(i).getPrecio_unidad(), 2);
            precioTotal = Convert.format(articulos.get(i).getPrecioTotal(), 2);
            precioConIva = Convert.format(articulos.get(i).getPrecioTotalIVA(), 2);

            gridPrincipal.setValueAt(articulos.get(i).getNombre(), i, 0);
            gridPrincipal.setValueAt(cantidad, i, 1);
            gridPrincipal.setValueAt(precioUnidad, i, 2);
            gridPrincipal.setValueAt(precioTotal, i, 3);
            gridPrincipal.setValueAt(precioConIva, i, 4);

        }
    }

}
